spring:
  application:
    name: security-service

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http:/localhost:8761/eureka}
  instance:
    prefer-ip-address: true